use_frameworks!

target 'SDWebImageLottieCoder_Example' do
  platform :ios, '9.0'
  pod 'SDWebImageLottieCoder', :path => '../'

  target 'SDWebImageLottieCoder_Tests' do
    inherit! :search_paths

    
  end
end

target 'SDWebImageLottieCoder-Example-macOS' do
  platform :osx, '10.10'
  pod 'SDWebImageLottieCoder', :path => '../'
end